name: CI

on:
  push:
    branches:
      - master
      - release/**
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        cxx-compiler: [cl, g++, clang++]
        compiler-version: [default, 8]

        build-type: [Debug, Release]
        include:
          - cxx-compiler: cl
            c-compiler: cl

          - cxx-compiler: clang++
            c-compiler: clang

          - cxx-compiler: g++
            c-compiler: gcc

        exclude:
          - os: windows-latest
            cxx-compiler: g++

          - os: windows-latest
            cxx-compiler: clang++

          - os: windows-latest
            cxx-compiler: cl
            compiler-version: 8

          - os: ubuntu-latest
            cxx-compiler: cl

          - os: ubuntu-latest
            cxx-compiler: g++
            compiler-version: default

          - os: ubuntu-latest
            cxx-compiler: clang++
            compiler-version: default

          - os: macos-latest
            cxx-compiler: g++

          - os: macos-latest
            cxx-compiler: cl

          - os: macos-latest
            cxx-compiler: clang++
            compiler-version: 8

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
      - run: sudo apt-get update
        if: matrix.os == 'ubuntu-latest'

      - name: Install Compiler
        shell: pwsh
        run: |
          $compiler = '${{ matrix.cxx-compiler }}'
          $version = '${{ matrix.compiler-version }}'

          if ($version -ne 'default') {
            sudo apt-get install "$compiler-$version" -y
            Invoke-Expression "$compiler-$version --version"
          }
        if: matrix.os == 'ubuntu-latest'

      - name: Install Conan
        run: |
          pip3 install conan
          conan --version

      - name: Set CXX and CC
        shell: pwsh
        run: |
          $cxx_compiler = '${{ matrix.cxx-compiler }}'
          $c_compiler = '${{ matrix.c-compiler }}'
          $version = '${{ matrix.compiler-version }}'

          if ($version -ne 'default') {
            $cxx_compiler = "$cxx_compiler-$version"
            $c_compiler = "$c_compiler-$version"
          }

          echo "::set-env name=CXX::$cxx_compiler"
          echo "::set-env name=CC::$c_compiler"

      - name: Create Default Conan Profile
        shell: pwsh
        run: |
          if ($Env:CXX -eq 'cl')
          {
            $Env:CXX = ''
            $Env:CC = ''
          }
          conan profile new default --detect

      - name: Build and Install Dependencies
        run: |
          mkdir build
          cd build
          conan install .. --build missing -s build_type=${{ matrix.build-type }} -pr default -pr ../tools/conan/build_tools -g virtualbuildenv

      - name: Fix Conan Virtualenv Scripts
        shell: pwsh
        run: |
          Get-ChildItem ./*activate*.ps1 | ForEach-Object {
            $content = (get-content -Path $_ | Select-String -Pattern '_old_conan_prompt' -NotMatch)
            Set-Content -Path $_ -Value $content
          }
        if: matrix.os == 'windows-latest'

      - name: Activate Conan Environment
        shell: pwsh
        run: |
          cd build

          ./activate_build.ps1
          ./activate.ps1

          Get-ChildItem Env: | ForEach-Object {
            $name = $_.Name
            $value = $_.Value
            echo "::set-env name=$name::$value"
          }
        if: matrix.os == 'windows-latest'

      - name: Activate Conan Environment
        shell: bash
        run: |
          cd build

          source ./activate_build.sh
          source ./activate.sh

          while IFS='=' read -r name value ; do
            echo "::set-env name=$name::$value"
          done < <(env)
        if: matrix.os != 'windows-latest'

      - name: Build
        run: |
          cd build
          which cmake
          cmake --version

          cmake .. -GNinja -DCMAKE_BUILD_TYPE:STRING="${{ matrix.build-type }}" -DBUILD_TESTS=ON
          cmake --build . --config ${{ matrix.build-type }}

      - name: Test
        run: |
          cd build
          ctest --output-on-failure -C ${{ matrix.build-type }}
